version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: element-ui
    versions:
    - 2.15.0
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: lodash
    versions:
    - 4.17.20
